default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  timeout: 5000
  min_messages: warning
  pool: <%= ENV.fetch("DB_POOL", 5) %>

development:
  <<: *default
  database: patients_development

test:
  <<: *default
  database: patients_test

production:
  <<: *default
  database: patients_production
